services:
  db:
    image: postgres:17.5-alpine
    container_name: postgres_container
    environment:
      - POSTGRES_DB=creditdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: redis_container
    ports:
      - "6379:6379"

volumes:
  db_data: