# Generated by Django 4.2.23 on 2025-07-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='monthly_repayment',
            new_name='monthly_installment',
        ),
    ]
